SE-588: checkpoint
finbourne/performance-engine-poc pull request #4
Opened 2020-12-07 22:03 UTC by slemasne

# Pull Request Checklist

- [x] Read the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x] Tests pass
- [x] Raised the PR against the `master` branch

# Description of the PR

Adding GHA tests

2020-12-22 12:10 UTC, rizwansaeed requested changes

2020-12-22 12:10 UTC, rizwansaeed commented on .github/workflows/build-and-test.yaml
> +    branches: [ develop ]
there is only `master` for this repo

2021-01-11 09:52 UTC, slemasne commented on .github/workflows/build-and-test.yaml
> +    branches: [ develop ]
Updated.

2021-01-11 09:52 UTC, rizwansaeed approved these changes

2021-01-11 09:54 UTC, merged